DETECT_CHAPTER_END = [
    {
        "task_name": "Part 1 Chapter END [29]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part1-Chapter29.png",
        "roi": [765, 346, 114, 62],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
        {
        "task_name": "Part 1 Chapter END [29 HARD]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part1-Chapter29_Hard.png",
        "roi": [765, 346, 114, 62],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 2 Chapter END [66]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part2-Chapter66.png",
        "roi": [768, 345, 115, 86],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 3 Chapter END [110]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part3-Chapter110.png",
        "roi": [777, 350, 99, 66],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 4 Chapter END [154]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part4-Chapter154.png",
        "roi": [799, 348, 98, 60],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 5 Chapter END [180]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part5-Chapter180.png",
        "roi": [756, 282, 92, 52],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 6 Chapter END [204]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part6-Chapter204.png",
        "roi": [793, 282, 92, 55],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 7 Chapter END [229]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part7-Chapter229.png",
        "roi": [771, 345, 109, 64],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 8 Chapter END [247]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part8-Chapter247.png",
        "roi": [772, 346, 108, 63],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 9 Chapter END [273]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part9-Chapter273.png",
        "roi": [749, 281, 114, 59],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
        {
        "task_name": "Part 9 Chapter END [273 HARD]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part9-Chapter273_Hard.png",
        "roi": [749, 281, 114, 59],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 10 Chapter END [299]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part10-Chapter299.png",
        "roi": [769, 347, 115, 54],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 11 Chapter END [320]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part11-Chapter320.png",
        "roi": [748, 284, 111, 61],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 12 Chapter END [352]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part12-Chapter352.png",
        "roi": [784, 349, 88, 72],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 13 Chapter END [387]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part13-Chapter387.png",
        "roi": [762, 283, 85, 56],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 14 Chapter END [398]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part14-Chapter398.png",
        "roi": [418, 348, 126, 79],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 15 Chapter END [410]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part15-Chapter410.png",
        "roi": [644, 278, 120, 75],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 16 Chapter END [421]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part16-Chapter421.png",
        "roi": [425, 347, 122, 75],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
        {
        "task_name": "Part 17 Chapter END [436]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part17-Chapter436.png",
        "roi": [759, 346, 129, 80],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 18 Chapter END [449]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part18-Chapter449.png",
        "roi": [704, 344, 136, 83],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 19 Chapter END [464]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part19-Chapter464.png",
        "roi": [757, 350, 122, 75],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 20 Chapter END [483]",
        "type": "template",
        "template_path": "templates/Easy-Hard/Part20-Chapter483.png",
        "roi": [739, 278, 137, 88],
        "click_location_str": "76,480",
        "use_match_position": False,
"confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Part 21 Chapter END [502] SWITCH TO HARD",
        "type": "pixel",
        "click_location_str": "76,480",
        "search_array": ["227,71","#000000","235,74","#000000","239,88","#060606","234,87","#000000","230,87","#000000","794,342","#0199ff","528,200","#51b7dd"],
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3,
        "HardStory": True,  # Switches to HardStory_tasks
    },
            {
        "task_name": "Part 21 Hard Chapter END [502] SWITCH TO SIDE",
        "type": "pixel",
        "click_location_str": "0,0",
        "search_array": ["227,71","#000000","235,74","#000000","239,88","#060606","234,87","#000000","230,87","#000000","794,342","#0199ff","267,190","#981e3b"],
        "use_match_position": False,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3,
        "SideStory": True,  # Switches to SideStory_tasks
    },



    # Side Story Easy + HARD
        {
        "task_name": "Side-Story Part 1 Chapter END [40]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part1-Chapter40_Easy.png",
        "roi": [779, 280, 117, 68],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 2 Chapter END [77]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part2-Chapter77_Easy.png",
        "roi": [775, 346, 102, 63],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 3 Chapter END [114]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part3-Chapter114_Easy.png",
        "roi": [750, 281, 107, 67],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 4 Chapter END [39]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part4-Chapter39_Easy.png",
        "roi": [770, 327, 120, 88],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 5 Chapter END [74]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part5-Chapter74_Easy.png",
        "roi": [796, 318, 127, 112],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
        {
        "task_name": "Side-Story Part 5 Chapter HARD END [74]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part5-Chapter74_Hard.png",
        "roi": [796, 318, 127, 112],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },


    {
        "task_name": "Side-Story Part 6 Chapter END [36]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part6-Chapter36_Easy.png",
        "roi": [791, 266, 125, 96],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 7 Chapter END [71]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part7-Chapter71_Easy.png",
        "roi": [745, 263, 120, 97],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 8 Chapter END [33]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part8-Chapter33_Easy.png",
        "roi": [788, 337, 123, 76],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 9 Chapter END [33]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part9-Chapter33_Easy.png",
        "roi": [744, 274, 120, 70],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 10 Chapter END [33]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part10-Chapter33_Easy.png",
        "roi": [751, 249, 114, 90],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 11 Chapter END [36]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part11-Chapter36_Easy.png",
        "roi": [764, 325, 124, 91],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 12 Chapter END [15]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part12-Chapter15_Easy.png",
        "roi": [766, 328, 118, 78],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 13 Chapter END [35]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part13-Chapter35_Easy.png",
        "roi": [699, 334, 125, 95],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 14 Chapter END [65]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part14-Chapter65_Easy.png",
        "roi": [767, 326, 125, 79],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 15 Chapter END [95]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part15-Chapter95_Easy.png",
        "roi": [783, 262, 120, 76],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 16 Chapter END [133]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part16-Chapter133_Easy.png",
        "roi": [704, 336, 134, 88],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 17 Chapter END [166]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part17-Chapter166_Easy.png",
        "roi": [710, 318, 139, 93],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
        {
        "task_name": "Side-Story Part 17 HARD Chapter END [166]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part17-Chapter166_Hard.png",
        "roi": [710, 318, 139, 93],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 18 Chapter END [192]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part18-Chapter192_Easy.png",
        "roi": [769, 258, 139, 120],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 19 Chapter END [226]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part19-Chapter226_Easy.png",
        "roi": [796, 327, 102, 74],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 20 Chapter END [29]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part20-Chapter29_Easy.png",
        "roi": [752, 339, 128, 84],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 21 Chapter END [58]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part21-Chapter58_Easy.png",
        "roi": [753, 275, 99, 82],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 22 Chapter END [87]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part22-Chapter87_Easy.png",
        "roi": [775, 331, 109, 76],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "sleep": 3
    },
    {
        "task_name": "Side-Story Part 23 Chapter END [117] Final Part [Switch To Hard]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part23-Chapter117_Easy.png",
        "roi": [699, 324, 139, 115],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
    },

       {
        "task_name": "Side-Story Part 24 Chapter END [153] Final Part [Switch To Hard]",
        "type": "template",
        "template_path": "templates/Side-Story/S_Part24-Chapter153_Easy.png",
        "roi": [762, 328, 136, 92],
        "click_location_str": "76,480",
        "use_match_position": False,
        "confidence": 0.90,
        "priority": 5,
        "cooldown": 5.0,
        "HardStory": True,
    },

]