# tasks/guild_tasks.py - Complete guild tutorial and rejoin tasks

GUILD_TUTORIAL_TASKS = [
    {
        "task_name": "Detect Game Updated! [Game Update]",
        "type": "pixel",
        "click_location_str": "480,373",
        "search_array": ["249,152","#0d12b5","264,166","#e60012","216,260","#ffffff","316,268","#ffffff","645,262","#ffffff","744,266","#ffffff"],
        "priority": 1,
        "cooldown": 999.0,
        "sleep": 3,
    },
    {
        "task_name": "Click [Guild Icon]",
        "type": "template",
        "template_path": "templates/Guild/GuildIcon.png",
        "roi": [442, 430, 109, 108],
        "confidence": 0.70,
        "use_match_position": True,
        
        "priority": 15,
        "cooldown": 5.0,
    },
    {
        "task_name": "Click [Join]",
        "type": "pixel",
        "click_location_str": "814,173",
        "search_array": ["801,173","#fbfcff","807,87","#485563","860,88","#ffffff"],
        
        "priority": 20,
        "cooldown": 5.0,
        "sleep": 3,
    },
    {
        "task_name": "Click [OK]",
        "type": "template",
        "template_path": "templates/Guild/OKGUILD.png",
        "roi": [535, 386, 162, 49],
        "confidence": 0.80,
        "use_match_position": True,
        
        "shared_detection": True,
        "priority": 25,
        "cooldown": 5.0,
    },
    {
        "task_name": "Click [Guild TOP]",
        "type": "template",
        "template_path": "templates/Guild/GuildTOP.png",
        "roi": [321, 337, 312, 59],
        "confidence": 0.90,
        "use_match_position": True,
        "priority": 30,
        "cooldown": 5.0,
        "sleep": 3,
    },
       {
        "task_name": "Leave [Guild Menu TOP]",
        "type": "pixel",
        "click_location_str": "31,27", 
        "search_array": ["890,442","#ffa146","884,471","#ecbca8","842,434","#24252b","778,522","#13178c"],
        "BackToStory": True,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 5,
    },
]

Guild_Rejoin = [
    {
        "task_name": "Detect Game Updated! [Game Update]",
        "type": "pixel",
        "click_location_str": "480,373",
        "search_array": ["249,152","#0d12b5","264,166","#e60012","216,260","#ffffff","316,268","#ffffff","645,262","#ffffff","744,266","#ffffff"],
        "priority": 1,
        "cooldown": 999.0,
        "sleep": 3,
    },
    {
        "task_name": "Click Join Button",
        "type": "template",
        "template_path": "templates/Guild/Join.png",
        "roi": [772, 116, 79, 399],
        "confidence": 0.80,
        "use_match_position": True,
        
        "shared_detection": True,
        "priority": 15,
        "cooldown": 5.0,
        "sleep": 3,
    },
    {
        "task_name": "Click Refresh",
        "type": "pixel",
        "click_location_str": "856,84",
        "search_array": ["859,88","#ffffff","861,78","#4d555c","876,100","#dedddd"],
        "priority": 10,
        "cooldown": 5.0,
        "sleep": 3,
    },
    {
        "task_name": "Click [Guild TOP]",
        "type": "template",
        "template_path": "templates/Guild/GuildTOP.png",
        "roi": [321, 337, 312, 59],
        "confidence": 0.90,
        "use_match_position": True,
        "NeedGuildTutorial": True,
        "priority": 25,
        "cooldown": 5.0,
        "sleep": 3,
    },
]