# tasks/restarting_tasks.py - Tasks for game startup and initial navigation

Restarting_Tasks = [
    {
        "task_name": "Click[Back] In Selling Character Window",
        "type": "pixel",
        "click_location_str": "23,22",
        "search_array": ["216,512","#e24601","74,26","#ffffff","24,21","#ffffff","53,27","#ffffff"],
        "isLogical": False,
    },
    {
        "task_name": "Click [Thank You] For Mod Menu",
        "type": "pixel",
        "click_location_str": "434,470",
        "search_array": ["265,470","#1c262b","338,469","#ffffff"],
        "isLogical": False,
    },
    {
        "task_name": "Click [Game Start]",
        "type": "pixel",
        "click_location_str": "477,452",
        "search_array": ["880,490","#515151","937,512","#e60012"],
        "isLogical": False,
    },
    {
        "task_name": "Click [Game Start 2]",
        "type": "pixel",
        "click_location_str": "471,450",
        "search_array": ["845,505","#fdfdfd","856,513","#e81828","14,21","#ffffff"],
        "isLogical": False,
    },
    {
        "task_name": "Click [No] For Entering Existing Quest",
        "type": "template",
        "template_path": "templates/No.png",
        "roi": [252, 339, 174, 57],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Skip Any New Events/Windows Opened By Clicking [OK]",
        "type": "template",
        "template_path": "templates/OK.png",
        "roi": [27, 229, 918, 272],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Open [SOLO] Menu",
        "type": "template",
        "template_path": "templates/Solo.png",
        "roi": [814, 420, 142, 118],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Exit News",
        "type": "template",
        "template_path": "templates/Exit.png",
        "roi": [731, 0, 228, 133],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Login Bonus Begginer",
        "type": "pixel",
        "click_location_str": "534,338",
        "search_array": ["195,93","#e50012","182,82","#0d12b4","334,79","#191925"],
        "isLogical": False,
    },
    {
        "task_name": "Login Bonus",
        "type": "pixel",
        "click_location_str": "626,510",
        "search_array": ["405,36","#191925","483,36","#191925","255,47","#e50012","255,35","#0d12b4"],
        "isLogical": False,
    },
]