# tasks/shared_tasks.py - Tasks that work with all task sets

Shared_Tasks = [
    {
        "task_name": "Click [Close] for Hard Mode Unlocked",
        "type": "template",
        "template_path": "templates/Close.png",
        "roi": [326, 340, 302, 55],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Click [Skip]",
        "type": "template",
        "template_path": "templates/Skip.png",
        "roi": [830, 1, 129, 59],
        "confidence": 0.70,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Go To Purchase Tickets",
        "type": "template",
        "template_path": "templates/PurchaseTickets.png",
        "roi": [390, 341, 169, 55],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Click 25 Tickets",
        "type": "template",
        "template_path": "templates/25Tickets.png",
        "roi": [194, 319, 564, 129],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Confirm Ticket Purchase",
        "type": "template",
        "template_path": "templates/Purchase.png",
        "roi": [534, 343, 174, 56],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Skip Any New Events/Windows Opened By Clicking [OK]",
        "type": "template",
        "template_path": "templates/OK.png",
        "roi": [2, 285, 559, 244],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Click [Resume] When Game Stopped Randomly",
        "type": "template",
        "template_path": "templates/Resume.png",
        "roi": [592, 460, 165, 54],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
    {
        "task_name": "Connection Error - Retry-OutGame",
        "type": "template",
        "template_path": "templates/Retry_Connection_Blue.png",
        "roi": [64, 254, 888, 239],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },
        {
        "task_name": "Connection Error - Retry-InsideGame",
        "type": "template",
        "template_path": "templates/Retry_Connection_Red.png",
        "roi": [64, 254, 888, 239],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
    },

]