# tasks/shared_tasks.py - Complete shared tasks with smart detection

Shared_Tasks = [
    # HIGHEST PRIORITY - Connection/Network Issues (Priority 1-5)
    {
        "task_name": "Connection Error - Retry-OutGame",
        "type": "template",
        "template_path": "templates/Shared/Retry_Connection_Blue.png",
        "roi": [64, 254, 888, 239],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
        "shared_detection": True,
        "priority": 1,
        "cooldown": 5.0,  # Long cooldown to prevent connection spam
    },
    {
        "task_name": "Connection Error - Retry-InsideGame",
        "type": "template",
        "template_path": "templates/Shared/Retry_Connection_Red.png",
        "roi": [64, 254, 888, 239],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
        "shared_detection": True,
        "priority": 1,
        "cooldown": 5.0,
    },
    {
        "task_name": "Click [Resume] When Game Stopped Randomly",
        "type": "template",
        "template_path": "templates/Shared/Resume.png",
        "roi": [592, 460, 165, 54],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
        "shared_detection": True,
        "priority": 2,
        "cooldown": 3.0,
    },
       {
        "task_name": "Download Data [Game Update]",
        "type": "pixel",
        "click_location_str": "620,372",
        "search_array": ["385,152","#191925","522,153","#191925","574,156","#191925","701,165","#e60012","708,153","#0d12b5"],
        "use_match_position": True,
        "isLogical": False,
        "shared_detection": True,
        "priority": 1,
        "cooldown": 1.0,
    },
    
    # HIGH PRIORITY - UI Elements/Popups (Priority 5-10)
    {
        "task_name": "Click [Skip]",
        "type": "template",
        "template_path": "templates/Shared/Skip.png",
        "roi": [830, 1, 129, 59],
        "confidence": 0.70,
        "use_match_position": True,
        "isLogical": False,
        "shared_detection": True,
        "priority": 5,
        "cooldown": 3.0,  # Prevent skip button spam
    },
    {
        "task_name": "Click [Close] for Hard Mode Unlocked",
        "type": "template",
        "template_path": "templates/Shared/Close.png",
        "roi": [326, 340, 302, 55],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
        "shared_detection": True,
        "priority": 8,
        "cooldown": 2.0,
    },
    
    # MEDIUM PRIORITY - Store/Purchase Actions (Priority 40-50)
    {
        "task_name": "Go To Purchase Tickets",
        "type": "template",
        "template_path": "templates/Purchase_Tickets/PurchaseTickets.png",
        "roi": [390, 341, 169, 55],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
        "priority": 40,
        "cooldown": 2.0,
    },
    {
        "task_name": "Click 25 Tickets",
        "type": "template",
        "template_path": "templates/Purchase_Tickets/25Tickets.png",
        "roi": [194, 319, 564, 129],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
        "priority": 45,
        "cooldown": 2.0,
    },
    {
        "task_name": "Confirm Ticket Purchase",
        "type": "template",
        "template_path": "templates/Purchase_Tickets/Purchase.png",
        "roi": [534, 343, 174, 56],
        "confidence": 0.90,
        "use_match_position": True,
        "isLogical": False,
        "priority": 45,
        "cooldown": 2.0,
    },

        {
        "task_name": "Click [Prepare To Battle]",
        "type": "pixel",
        "click_location_str": "693,492",
        "search_array": ["527,486","#0c3be2","567,490","#ffffff","660,493","#ffffff","754,492","#ffffff"],
        "isLogical": False,
        "priority": 5,
        "cooldown": 2.0,
    },
    {
        "task_name": "Click [Start Quest]",
        "type": "pixel",
        "click_location_str": "715,497",
        "search_array": ["583,490","#ffffff","652,491","#0d3de4","671,498","#ffffff","735,496","#ffffff"],
        "isLogical": False,
        "priority": 5,
        "cooldown": 2.0,
    },

     {
        "task_name": "Click New Record Word To Open Next Quest Menu",
        "type": "pixel",
        "click_location_str": "449,503",
        "search_array": ["833,35","#ff0000","819,54","#ffffff","834,74","#ff0000"],
        "isLogical": False,
        "priority": 20,
    },
    {
        "task_name": "Click [Next Quest]",
        "type": "pixel",
        "click_location_str": "756,508",
        "search_array": ["713,512","#ffffff","760,507","#ffffff","698,496","#1e46f2"],
        "isLogical": False,
        "priority": 5,
    },
    {
        "task_name": "New Record Quest Obtained",
        "type": "pixel",
        "click_location_str": "478,281",
        "search_array": ["170,273","#fefefe","810,187","#ff0000","798,209","#ffffff"],
        "isLogical": False,
        "priority": 20,
    },
]