Sort_Multi_Select_Garbage_First_Tasks = [
    {
        "task_name": "Click [Edit] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "384,494",
        "search_array": ["380,481","#e1773a","367,462","#323348","362,524","#ffffff"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
        {
        "task_name": "Choose [AnyCharacter] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "483,200",
        "search_array": ["74,24","#ffffff","117,77","#ffffff","177,86","#e60012","787,91","#ffffff"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
            {
        "task_name": "Click [Power Up][Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "197,491",
        "search_array": ["151,496","#ffffff","229,496","#ffffff","236,475","#31fc24"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
            {
        "task_name": "Click [Soul Tree] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "120,209",
        "search_array": ["851,239","#90909c","585,235","#90909c","323,231","#90909c"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
            {
        "task_name": "Click [Level] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "378,209",
        "search_array": ["119,211","#00ff00","591,243","#90909c","851,234","#90909c"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
            {
        "task_name": "Click [Ascension] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "636,210",
        "search_array": ["120,211","#00ff00","378,211","#00ff00","849,242","#90909c"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
                {
        "task_name": "Click [Confirm][Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "647,493",
        "search_array": ["120,211","#00ff00","378,211","#00ff00","636,211","#00ff00"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
                        {
        "task_name": "Click [Multi Select] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "395,443",
        "search_array": ["457,444","#454e57","422,451","#e60012","392,428","#ffffff"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
                        {
        "task_name": "Change [Level 1 => Level 4] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "545,213",
        "search_array": ["210,217","#eb4c01","120,218","#ec4e01","137,212","#ffffff"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
                        {
        "task_name": "Change [ Lvl1 => ALL] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "387,318",
        "search_array": ["265,322","#ec4c01","129,322","#ec4c01"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
                        {
        "task_name": "Click [] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "381,436",
        "search_array": ["261,433","#ec4e01","267,433","#ec4e01"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
                        {
        "task_name": "Swipe All Tasks Are ON [Lvl4 ~ ALL ~ ALL] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "0,0",
        "search_array": ["456,432","#ec4c01","459,322","#ec4c01","590,218","#ec4e01"],
        "multi_click": True,
        "min_matches_for_swipe": 2,
        "swipe_command": "shell input swipe 443 400 443 140 900",
        "isLogical": False,
        "priority": 1,
        "cooldown": 0.1,
        "sleep": 3,
    },
                        {
        "task_name": "Change [Only Raid Character => ALL Characters] [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "731,415",
        "search_array": ["332,421","#ec4c01","836,420","#3e4e5f"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "sleep": 3,
    },
                        {
        "task_name": "Click [Select] For Confirming The Filter [Sort Multi-Select Garbage]",
        "type": "pixel",
        "click_location_str": "652,484",
        "search_array": ["838,421","#ec4c01","734,418","#ffffff","739,419","#ffffff"],
        "isLogical": False,
        "priority": 1,
        "cooldown": 5.0,
        "json_Sort_Multi_Select_Garbage_First": True,
        "Upgrade_Characters_Level_Tasks": True,
        "sleep": 3,
    },

]
